const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("bellwrightMods", {
  getAppInfo: () => ipcRenderer.invoke("app:getInfo"),
  minimizeWindow: () => ipcRenderer.send("window:minimize"),
  toggleMaximizeWindow: () => ipcRenderer.send("window:toggleMaximize"),
  closeWindow: () => ipcRenderer.send("window:close"),
  getState: () => ipcRenderer.invoke("mods:getState"),
  onGameRunningChanged: (callback) => ipcRenderer.on("mods:gameRunningChanged", (_event, gameRunning) => callback(gameRunning)),
  onNativeRuntimeChanged: (callback) => ipcRenderer.on("mods:nativeRuntimeChanged", (_event, status) => callback(status)),
  enable: (payload) => ipcRenderer.invoke("mods:enable", payload),
  disable: (payload) => ipcRenderer.invoke("mods:disable", payload),
  setLoadOrder: (payload) => ipcRenderer.invoke("mods:setLoadOrder", payload),
  showTooltip: (payload) => ipcRenderer.invoke("mods:showTooltip", payload),
  hideTooltip: () => ipcRenderer.invoke("mods:hideTooltip"),
  onTooltip: (callback) => ipcRenderer.on("tooltip:setMod", (_event, mod) => callback(mod)),
  listPresets: () => ipcRenderer.invoke("presets:list"),
  savePreset: (payload) => ipcRenderer.invoke("presets:save", payload),
  loadPreset: (id) => ipcRenderer.invoke("presets:load", id),
  deletePreset: (id) => ipcRenderer.invoke("presets:delete", id),
  copyPresetShareCode: (id) => ipcRenderer.invoke("presets:copyShareCode", id),
  inspectPresetShareCode: (code) => ipcRenderer.invoke("presets:inspectShareCode", code),
  importPresetShareCode: (code) => ipcRenderer.invoke("presets:importShareCode", code),
  openModsFolder: () => ipcRenderer.invoke("mods:openModsFolder"),
  openWorkshopItem: (workshopId) => ipcRenderer.invoke("mods:openWorkshopItem", workshopId),
  launchGame: () => ipcRenderer.invoke("mods:launchGame"),
  openDonate: () => ipcRenderer.invoke("app:openDonate"),
  openDiscord: () => ipcRenderer.invoke("app:openDiscord"),
  updateLauncher: () => ipcRenderer.invoke("app:updateLauncher"),
  onUpdateProgress: (callback) => ipcRenderer.on("app:updateProgress", (_event, progress) => callback(progress))
});
